import turtle
turtle.ht()
turtle.circle(50)
turtle.penup()
turtle.goto(100,0)
turtle.pendown()
turtle.circle(50)

turtle.penup()
turtle.goto(-100,0)
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.goto(-50,-50)
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.goto(50,-50)
turtle.pendown()
turtle.circle(50)

turtle.mainloop()